/** Colours the pixel art is drawn in. `c` follows the surrounding text colour. */
const PALETTE: Record<string, string> = {
  c: 'currentColor',
  k: '#1a1a1a',
  w: '#ffffff',
  s: '#c9c5bc',
  g: '#8a867d',
  n: '#0c2a6b',
  b: '#3a6ea5',
  L: '#a7d977',
  G: '#4f9a3c',
  D: '#2d6a2f',
  t: '#8a5a2b',
  T: '#5a3717',
  Y: '#fff2a8',
  y: '#f1c232',
  o: '#b8860b',
  r: '#d4251c',
  R: '#8f130d',
  a: '#f5c518',
  e: '#e8b24a',
  E: '#9c6a14',
  h: '#fff7cf',
};

/** One string per row, one character per pixel; `.` is transparent. */
const ART = {
  tree: [
    '.....kkkkk......',
    '...kkLLLGGkk....',
    '..kLLLGGGGGGk...',
    '.kLLGGGGGGGGDk..',
    '.kLGGGGGGGGGDk..',
    'kLGGGGGGGGGGDDk.',
    'kGGGDGGGGDGDDDk.',
    'kGGGGDGGGDGGDDk.',
    '.kGGGDDDDDGDDk..',
    '..kkDDDtDDDkk...',
    '....kkttTkk.....',
    '.....kttTk......',
    '.....kttTk......',
    '...kktttTTkk....',
    '..kttkk.kkTTk...',
    '..kk.......kk...',
  ],
  doc: [
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwksk...',
    '..kwwwwwwwkkkk..',
    '..kwwwwwwwwwwkg.',
    '..kwwwnnnwwwwkg.',
    '..kwwnwwwnwwwkg.',
    '..kwwwwwwnwwwkg.',
    '..kwwwwwnwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwwwwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwwwwwwwkg.',
    '..kkkkkkkkkkkkg.',
    '...gggggggggggg.',
  ],
  folder: [
    '................',
    '................',
    '.kkkkk..........',
    'kYYYYYk.........',
    'kYyyyyYkkkkkkkk.',
    'kYyyyyyYYYYYYYYk',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kooooooooooooook',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  key: [
    '................',
    '................',
    '................',
    '..kkkk..........',
    '.khhheE.........',
    'khekkeEk........',
    'khk..kekkkkkkkk.',
    'kek..kehhhhhhhek',
    'keEkkeEEEEEEEEEk',
    '.kEEEEkkkkEkEEk.',
    '..kkkk....kkkEk.',
    '............kk..',
    '................',
    '................',
    '................',
    '................',
  ],
  user: [
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....khhhhk.....',
    '.....khhhhk.....',
    '.....khhhhk.....',
    '......kkkk......',
    '....kkbbbbkk....',
    '...kbbbbbbbbk...',
    '..kbbbbbbbbbbk..',
    '..kbbbbbbbbbbk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  error: [
    '................',
    '.....kkkkk......',
    '...kkrrrrrkk....',
    '..krrrrrrrrrk...',
    '.krrwwrrrwwrRk..',
    '.krrrwwrwwrrRk..',
    'krrrrrwwwrrrrRk.',
    'krrrrrrwrrrrrRk.',
    'krrrrrwwwrrrrRk.',
    '.krrrwwrwwrrRk..',
    '.krrwwrrrwwrRk..',
    '..krrrrrrrrRk...',
    '...kkRRRRRkk....',
    '.....kkkkk......',
    '................',
    '................',
  ],
  warning: [
    '.......k........',
    '......kak.......',
    '......kak.......',
    '.....kaaak......',
    '.....kakak......',
    '....kaakaak.....',
    '....kaakaak.....',
    '...kaaakaaak....',
    '...kaaakaaak....',
    '..kaaaaaaaaak...',
    '..kaaaakaaaak...',
    '.kaaaaaaaaaaak..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  speaker: [
    '................',
    '................',
    '......kk........',
    '.....kwk.....k..',
    '....kwwk..k...k.',
    'kkkkwwwk...k..k.',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kkkkwwwk...k..k.',
    '....kwwk..k...k.',
    '.....kwk.....k..',
    '......kk........',
    '................',
    '................',
  ],
  speakerOff: [
    '................',
    '................',
    '......kk........',
    '.....kwk........',
    '....kwwk........',
    'kkkkwwwk.r...r..',
    'kssswwwk..r.r...',
    'kssswwwk...r....',
    'kssswwwk..r.r...',
    'kssswwwk.r...r..',
    'kkkkwwwk........',
    '....kwwk........',
    '.....kwk........',
    '......kk........',
    '................',
    '................',
  ],
  // Small glyphs, drawn in the text colour.
  minimize: ['........', '........', '........', '........', '........', '.cccccc.', '.cccccc.'],
  maximize: [
    'ccccccccc',
    'ccccccccc',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'ccccccccc',
  ],
  close: ['cc....cc', '.cc..cc.', '..cccc..', '...cc...', '..cccc..', '.cc..cc.', 'cc....cc'],
  arrowDown: ['ccccccc', '.ccccc.', '..ccc..', '...c...'],
  arrowUp: ['...c...', '..ccc..', '.ccccc.', 'ccccccc'],
  // The resize grip in a status bar's corner: three raised ridges.
  grip: [
    '..........wg',
    '.........wg.',
    '........wg..',
    '.......wg..w',
    '......wg..wg',
    '.....wg..wg.',
    '....wg..wg..',
    '...wg..wg..w',
    '..wg..wg..wg',
    '.wg..wg..wg.',
    'wg..wg..wg..',
    'g..wg..wg...',
  ],
  dots: ['cc', 'cc', '..', '..', 'cc', 'cc', '..', '..', 'cc', 'cc'],
  check: ['......c', '.....cc', 'c...ccc', 'cc.ccc.', 'ccccc..', '.ccc...', '..c....'],
} satisfies Record<string, string[]>;

export type PixelIconName = keyof typeof ART;

type PixelPath = { fill: string; d: string };
type PixelArt = { width: number; height: number; paths: PixelPath[] };

/** Merge each row into runs of one colour, so an icon is a path per colour, not a rect per pixel. */
function toPaths(rows: string[]): PixelPath[] {
  const byColour = new Map<string, string>();
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      const key = row[x];
      let run = 1;
      while (row[x + run] === key) run++;
      if (key !== '.') byColour.set(key, `${byColour.get(key) ?? ''}M${x} ${y}h${run}v1h-${run}z`);
      x += run;
    }
  });
  return [...byColour].map(([key, d]) => ({ fill: PALETTE[key], d }));
}

export const PIXEL_ART = Object.fromEntries(
  Object.entries(ART).map(([name, rows]) => [
    name,
    { width: rows[0].length, height: rows.length, paths: toPaths(rows) },
  ]),
) as Record<PixelIconName, PixelArt>;
