/** Colours the pixel art is drawn in. `c` follows the surrounding text colour. */
const PALETTE: Record<string, string> = {
  c: 'currentColor',
  k: '#1a1a1a',
  w: '#ffffff',
  s: '#c9c5bc',
  g: '#8a867d',
  n: '#0c2a6b',
  b: '#3a6ea5',
  L: '#a7d977',
  G: '#4f9a3c',
  D: '#2d6a2f',
  t: '#8a5a2b',
  T: '#5a3717',
  Y: '#fff2a8',
  y: '#f1c232',
  o: '#b8860b',
  r: '#d4251c',
  R: '#8f130d',
  a: '#f5c518',
  e: '#e8b24a',
  E: '#9c6a14',
  h: '#fff7cf',
  // A grey ramp for drawings that sit behind the text: dim, between, face, light.
  '1': '#8a867d',
  '2': '#b9b5ac',
  '3': '#d4d0c8',
  '4': '#e8e5de',
};

/**
 * An illustration rather than an icon: the world tree, roots and all, drawn at scale 4. It is
 * kept in colour here, which is easier to read and edit, and shown in greys (`toTones`).
 */
const WORLD_TREE = [
  '..............kkkk..............',
  '............kkLLLGkk............',
  '.......kkkkkLLLLGGGGkkkkk.......',
  '.....kkLGGGLLLLLGGGGGDGGGkk.....',
  '....kLLLLGGLLLLLLGGGGDLGGGGk....',
  '....kLLLLLGLLLLLLGGGGGDLGGGk....',
  '...kGLLLLLGLLLLLGGGGGGDLGGGGk...',
  '...kGLLLLGGGGLLGGGGGGGDGGGGGk...',
  '...kGGGGGGGGGGGGGGDGDDDGGGGDk...',
  '..kLLGGGDGGGGLLLGGGDDDDGLLGGGk..',
  '.kLLLLGGGDDGLLLLLGGGDDDLLLLGGGk.',
  'kLLLLLGGGGGLLLLLLGGGGDGDLLLGGGGk',
  'kGLLLLGLLLGGLLLLGGGGGDGGGDLGGGGk',
  'kGLLLGLLLLGGGLLGGGGGGDGGGGDGGGGk',
  'kGGGGGLLLLLGGGGGGGGGDDLGGGDGGGDk',
  'kGGGGGLLLLGGGGGGGGDDDDGGGGGDDDDk',
  '.kGGGGGGGGGDGGGGDDDDDDGGGGDDDDk.',
  '..kGDDGGGGGGDGGDDDDDDGGGDDDDDk..',
  '...kkkGGGGDDDDDDDDDDGGDDDDkkk...',
  '......kGGDDDDttttTTGGDDDDk......',
  '.......kkDDkkttttTTkkDDkk.......',
  '.........kk.kttttTTk.kk.........',
  '............kttttTTk............',
  '............kttttTTk............',
  '............kttttTTk............',
  '............kttttTTk............',
  '...........ktttttTTTk...........',
  '..........kttttttTTTTk..........',
  '.......kkktttttttTTTTTkkk.......',
  '....kkkttttTktttTTTktTTTTkkk....',
  '..kktttttTkkkkttTTkkkktTTTTTkk..',
  '.ktttTkkkk....ktTk....kkkktTTTk.',
  '.kkkkk.........kk.........kkkkk.',
];

/** Tone on tone, like the desktop wallpaper: each colour becomes the grey of the same depth. */
function toTones(rows: string[]): string[] {
  const tones: Record<string, string> = { k: '1', D: '2', T: '2', G: '3', t: '3', L: '4' };
  return rows.map((row) => row.replace(/./g, (key) => tones[key] ?? '.'));
}

/** One string per row, one character per pixel; `.` is transparent. */
const ART = {
  tree: [
    '.....kkkkk......',
    '...kkLLLGGkk....',
    '..kLLLGGGGGGk...',
    '.kLLGGGGGGGGDk..',
    '.kLGGGGGGGGGDk..',
    'kLGGGGGGGGGGDDk.',
    'kGGGDGGGGDGDDDk.',
    'kGGGGDGGGDGGDDk.',
    '.kGGGDDDDDGDDk..',
    '..kkDDDtDDDkk...',
    '....kkttTkk.....',
    '.....kttTk......',
    '.....kttTk......',
    '...kktttTTkk....',
    '..kttkk.kkTTk...',
    '..kk.......kk...',
  ],
  doc: [
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwksk...',
    '..kwwwwwwwkkkk..',
    '..kwwwwwwwwwwkg.',
    '..kwwwnnnwwwwkg.',
    '..kwwnwwwnwwwkg.',
    '..kwwwwwwnwwwkg.',
    '..kwwwwwnwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwwwwwwwkg.',
    '..kwwwwnwwwwwkg.',
    '..kwwwwwwwwwwkg.',
    '..kkkkkkkkkkkkg.',
    '...gggggggggggg.',
  ],
  folder: [
    '................',
    '................',
    '.kkkkk..........',
    'kYYYYYk.........',
    'kYyyyyYkkkkkkkk.',
    'kYyyyyyYYYYYYYYk',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kYyyyyyyyyyyyyok',
    'kooooooooooooook',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  key: [
    '................',
    '................',
    '................',
    '..kkkk..........',
    '.khhheE.........',
    'khekkeEk........',
    'khk..kekkkkkkkk.',
    'kek..kehhhhhhhek',
    'keEkkeEEEEEEEEEk',
    '.kEEEEkkkkEkEEk.',
    '..kkkk....kkkEk.',
    '............kk..',
    '................',
    '................',
    '................',
    '................',
  ],
  user: [
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....khhhhk.....',
    '.....khhhhk.....',
    '.....khhhhk.....',
    '......kkkk......',
    '....kkbbbbkk....',
    '...kbbbbbbbbk...',
    '..kbbbbbbbbbbk..',
    '..kbbbbbbbbbbk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  error: [
    '................',
    '.....kkkkk......',
    '...kkrrrrrkk....',
    '..krrrrrrrrrk...',
    '.krrwwrrrwwrRk..',
    '.krrrwwrwwrrRk..',
    'krrrrrwwwrrrrRk.',
    'krrrrrrwrrrrrRk.',
    'krrrrrwwwrrrrRk.',
    '.krrrwwrwwrrRk..',
    '.krrwwrrrwwrRk..',
    '..krrrrrrrrRk...',
    '...kkRRRRRkk....',
    '.....kkkkk......',
    '................',
    '................',
  ],
  warning: [
    '.......k........',
    '......kak.......',
    '......kak.......',
    '.....kaaak......',
    '.....kakak......',
    '....kaakaak.....',
    '....kaakaak.....',
    '...kaaakaaak....',
    '...kaaakaaak....',
    '..kaaaaaaaaak...',
    '..kaaaakaaaak...',
    '.kaaaaaaaaaaak..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  speaker: [
    '................',
    '................',
    '......kk........',
    '.....kwk.....k..',
    '....kwwk..k...k.',
    'kkkkwwwk...k..k.',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kssswwwk...k...k',
    'kkkkwwwk...k..k.',
    '....kwwk..k...k.',
    '.....kwk.....k..',
    '......kk........',
    '................',
    '................',
  ],
  speakerOff: [
    '................',
    '................',
    '......kk........',
    '.....kwk........',
    '....kwwk........',
    'kkkkwwwk.r...r..',
    'kssswwwk..r.r...',
    'kssswwwk...r....',
    'kssswwwk..r.r...',
    'kssswwwk.r...r..',
    'kkkkwwwk........',
    '....kwwk........',
    '.....kwk........',
    '......kk........',
    '................',
    '................',
  ],
  worldTree: toTones(WORLD_TREE),
  // Small glyphs, drawn in the text colour.
  minimize: ['........', '........', '........', '........', '........', '.cccccc.', '.cccccc.'],
  maximize: [
    'ccccccccc',
    'ccccccccc',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'c.......c',
    'ccccccccc',
  ],
  close: ['cc....cc', '.cc..cc.', '..cccc..', '...cc...', '..cccc..', '.cc..cc.', 'cc....cc'],
  arrowDown: ['ccccccc', '.ccccc.', '..ccc..', '...c...'],
  arrowUp: ['...c...', '..ccc..', '.ccccc.', 'ccccccc'],
  // The resize grip in a status bar's corner: three raised ridges.
  grip: [
    '..........wg',
    '.........wg.',
    '........wg..',
    '.......wg..w',
    '......wg..wg',
    '.....wg..wg.',
    '....wg..wg..',
    '...wg..wg..w',
    '..wg..wg..wg',
    '.wg..wg..wg.',
    'wg..wg..wg..',
    'g..wg..wg...',
  ],
  dots: ['cc', 'cc', '..', '..', 'cc', 'cc', '..', '..', 'cc', 'cc'],
  check: ['......c', '.....cc', 'c...ccc', 'cc.ccc.', 'ccccc..', '.ccc...', '..c....'],
} satisfies Record<string, string[]>;

export type PixelIconName = keyof typeof ART;

type PixelPath = { fill: string; d: string };
type PixelArt = { width: number; height: number; paths: PixelPath[] };

/** Merge each row into runs of one colour, so an icon is a path per colour, not a rect per pixel. */
function toPaths(rows: string[]): PixelPath[] {
  const byColour = new Map<string, string>();
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      const key = row[x];
      let run = 1;
      while (row[x + run] === key) run++;
      if (key !== '.') byColour.set(key, `${byColour.get(key) ?? ''}M${x} ${y}h${run}v1h-${run}z`);
      x += run;
    }
  });
  return [...byColour].map(([key, d]) => ({ fill: PALETTE[key], d }));
}

export const PIXEL_ART = Object.fromEntries(
  Object.entries(ART).map(([name, rows]) => [
    name,
    { width: rows[0].length, height: rows.length, paths: toPaths(rows) },
  ]),
) as Record<PixelIconName, PixelArt>;
